### ISSUE TITLE
onAuthStateChange not triggered when JWT expired

### ISSUE THREAD

**Issue by KirioXX** [supabase/supabase-flutter#452]
**Describe the bug**
We had this week quite a lot of users where the JWT expired.
There users where not logged out instead they had to close and reopen the app to trigger the logout.

In our logs we have seen a lot of these errors:
```txt
data:text/text;charset=utf-8,
PostgrestException(message: JWT expired, code: PGRST301, details: Unauthorized, hint: null)

When the exception was thrown, this was the stack:
0		PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323:0)
1		PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198:0)
2		PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400:0)


```

**To Reproduce**
1. Setup a listener to listen for onAuthStateChange (we use a [bloc cubit](https://bloclibrary.dev/#/coreconcepts?id=cubit) for that )
2. Login
3. Let the JWT expire
4. Try to make a request

**Expected behavior**
User is getting logged out either when the JWT expires or when the try to make a request.

**Screenshots**
-

**Version (please complete the following information):**
On Linux/macOS
Please run `dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"` in your project directory and paste the output here.
```
│   └── supabase_flutter...
│   └── supabase_flutter...
│   └── supabase_flutter...
│   ├── supabase_flutter...
│   ├── supabase_flutter...
│   └── supabase_flutter...
│   ├── supabase_flutter...
│   └── supabase_flutter...
│   ├── supabase_flutter...
│   └── supabase_flutter...
│   └── supabase_flutter...
│   └── supabase_flutter...
├── supabase_flutter 1.7.0
│   ├── supabase 1.6.3
│   │   ├── functions_client 1.1.1
│   │   ├── gotrue 1.6.0
│   │   ├── postgrest 1.2.3
│   │   ├── realtime_client 1.0.3
│   │   ├── storage_client 1.3.0
```

On Windows
Please run `dart pub deps | findstr "supabase gotrue postgrest storage_client realtime_client functions_client"` in your project directory and paste the output here.

**Additional context**

**Comment by Vinzent03** [comment]
`gotrue 1.6.0` got just a few minutes ago released. Do you really still experience this issue? What version of `gotrue` where the production app using? What jwt expiry time have you set?

**Comment by KirioXX** [comment]
Thanks for the quick response @Vinzent03.
That is a very good point the current production version is still on `gotrue 1.4.2`:
```txt
├── supabase_flutter 1.4.0
│   ├── supabase 1.5.1
│   │   ├── functions_client 1.0.2
│   │   ├── gotrue 1.4.2
│   │   ├── postgrest 1.2.2
│   │   ├── realtime_client 1.0.2
│   │   ├── storage_client 1.2.2
```
Could that be the issue?

**Comment by Vinzent03** [comment]
There was a fix in [1.5.6](https://github.com/supabase/gotrue-dart/blob/main/CHANGELOG.md#156) about jwt expiry margins. This may be the cause.

**Comment by KirioXX** [comment]
Thank you very much Vinzent03. 
We actually have a new release going out to the first users today, which uses 1.5.6.
I will keep you posted if the new version resolves it.

**Comment by Vinzent03** [comment]
It might be important to update to 1.5.7 though, depending on how important the session emitted by the inAuthStateChange stream is.

**Comment by KirioXX** [comment]
Sorry I meant we are on 1.5.7 😅

**Comment by KirioXX** [comment]
@Vinzent03 we rolled out our new app version to some test device. So far everything looks good.
But we got this error yesterday and it seems to be stuck in a loop:
```txt
data:text/text;charset=utf-8,
AuthException(message: Invalid Refresh Token: Refresh Token Not Found, statusCode: 400)

When the exception was thrown, this was the stack:
0		GotrueFetch.request (package:gotrue/src/fetch.dart:99:0)
1		GoTrueClient._callRefreshToken (package:gotrue/src/gotrue_client.dart:669:0)
2		GoTrueClient.recoverSession (package:gotrue/src/gotrue_client.dart:549:0)
3		SupabaseAuth.initialize (package:supabase_flutter/src/supabase_auth.dart:104:0)
4		Supabase.initialize (package:supabase_flutter/src/supabase.dart:91:0)
5		_initSupabase (package:tusks/main.dart:67:0)
6		main (package:tusks/main.dart:24:0)
7		main (package:tusks/main_production.dart:18:0)
```

Can that be related to the JWT issue?

**Comment by Vinzent03** [comment]
You should get logged out when this error comes up. You get this error for example when you sign out on another device.

**Comment by KirioXX** [comment]
Hi @Vinzent03, we had yesterday again a user that didn't get log out even though the request returned 401 codes.
Is there anything that we could miss when we listen to onAuthStateChange?

**Comment by Vinzent03** [comment]
We currently only sign out on the specific error message `Invalid Refresh Token: Refresh Token Not Found`. I don't know what the reason for a 401 response is. We emit the error via `addError` to the onAuthDtateChange stream, where you could react to that.

**Comment by KirioXX** [comment]
Thanks for the quick response @Vinzent03.
If it helps, this is full response:
```
Response
  Headers:
   access-control-allow-origin: "*"
   content-type: "application/json; charset=utf-8"
   x-kong-upstream-latency: "0"
   alt-svc: "h3=":443"; ma=86400, h3-29=":443"; ma=86400"
   via: "kong/2.8.1"
   server: "cloudflare"
   sb-gateway-version: "1"
   transfer-encoding: "chunked"
   cf-cache-status: "DYNAMIC"
   date: "Thu, 11 May 2023 21:51:43 GMT"
   x-kong-proxy-latency: "1"
   strict-transport-security: "max-age=2592000; includeSubDomains"
   connection: "keep-alive"
   cf-ray: "7c5da514af510fd3-LAX"
   vary: "Accept-Encoding"
   www-authenticate: "Bearer error="invalid_token", error_description="JWT expired""
  Body:
   code: "PGRST301"
   message: "JWT expired"
   details: null
   hint: null
```
The logs also say that there was 1 slow request before the failing once, could it be that the JWT was invalidated because the refresh request was to slow? Sadly I miss a couple network request logs.
