### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by gillesrusticity** [supabase/supabase-flutter#488]
**Describe the bug**
Cannot use Supabase with latest version of http package.

Here is my pubspec.yaml

```
name: app43
description: A Flutter project.
version: 0.0.80+80

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.0
  flutter_riverpod: ^2.3.6
  http: ^1.0.0
  uuid: ^3.0.6
  google_fonts: ^4.0.5
  shared_preferences: ^2.0.16
  data_table_2: ^2.3.10
  font_awesome_flutter: ^10.3.0
  date_format: ^2.0.7
  tinycolor2: ^3.0.1
  cron: ^0.5.1
  connectivity_plus: ^3.0.2
  sticky_headers: ^0.3.0+2
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
      - assets/images/
      - assets/localizations/
```

The error is get is : 

```
Because supabase_flutter 1.10.0 depends on http ^0.13.4 and no versions of supabase_flutter match >1.10.0 <2.0.0, supabase_flutter ^1.10.0 requires http ^0.13.4.
So, because app43 depends on both supabase_flutter ^1.10.0 and http ^1.0.0, version solving failed.
```

Flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on Ubuntu 20.04.6 LTS 5.4.0-148-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```
